#*******************************************************************************
# ADOBE SYSTEMS INCORPORATED
# Copyright 2008 Adobe Systems Incorporated
# All Rights Reserved.
#
# NOTICE:  Adobe permits you to use, modify, and distribute this file in
# accordance with the  terms of the Adobe license agreement accompanying it. If
# you have received this file from a source other than Adobe, then your use,
# modification, or distribution of it requires the prior written permission of
# Adobe.
#******************************************************************************/

###############################################################################
# STEP 1 - REQUIRED: Specify toolchain

DH_FLEX_SDK?=$(DH_TOOLS_DIR)/FlexSDK4.5.1

DH_TOOLS_DIR?=../../../../../tools
DH_PLATFORM_DIR?=$(DH_TOOLS_DIR)/platform/linux
DH_FLEX_BIN=$(DH_FLEX_SDK)/bin

#DH_WEBKIT_INCLUDES := `pkg-config --cflags webkitgtk-3.0`
#DH_WEBKIT_LIBS := `pkg-config --libs webkitgtk-3.0`

#DH_GTK_INCLUDES := `pkg-config --cflags gtk+-3.0`
#DH_GTK_LIBS := `pkg-config --libs gtk+-3.0`

define DH_resolve_path
  DH_search_path:=$$(if $(3),$$(DH_FLEX_BIN):)$$(PATH)
  $(1) ?= $$(shell PATH="$$(DH_search_path)" which $(2))
  ifeq "$$($(1))" ""
    ifeq "$$(findstring sdk,$(3))" "sdk"
      $$(warning warning: $(2) from the flex sdk not found)
      $$(warning the $(2) tool is necessary for signing extensions) 
    else
      $$(error error: locating $(2) for $(1))
    endif
  endif
endef

DH_CC=$(CC)
DH_CXX=$(CXX)
DH_AR=$(AR)
DH_LD=$(LD)
DH_RANLIB=$(RANLIB)
DH_STRIP=$(STRIP)
DH_ROOTFS_DIR=$(PKG_CONFIG_SYSROOT_DIR)
ROKU_PLATFORM=$(DH_ROOTFS_DIR)
DH_THIRDPARTY_LIBS := $(filter-out unix/curl, $(DH_THIRDPARTY_LIBS))
DH_THIRDPARTY_LIBS := $(filter-out unix/x86/openssl, $(DH_THIRDPARTY_LIBS))
DH_AVE_WEBKIT_MODULES :=
#$(eval $(call DH_resolve_path,DH_CC,gcc))
#$(eval $(call DH_resolve_path,DH_CXX,g++))
#$(eval $(call DH_resolve_path,DH_LD,ld))
#$(eval $(call DH_resolve_path,DH_AR,ar))
#$(eval $(call DH_resolve_path,DH_RANLIB,ranlib))
#$(eval $(call DH_resolve_path,DH_STRIP,strip))
$(eval $(call DH_resolve_path,DH_ZIP,zip))
$(eval $(call DH_resolve_path,DH_UNZIP,unzip))
#$(eval $(call DH_resolve_path,DH_COMPC,compc,sdk))
#$(eval $(call DH_resolve_path,DH_ADT,adt,sdk))

###############################################################################
# STEP 1.5 - REQUIRED: Specify the platform identifiers that are used by the
# ISystemDriver implementation and by the native extensions build system.

DH_PLATFORM_NAME := genericTV
DH_PLATFORM_ARCH := x86

###############################################################################
# STEP 2 - OPTIONAL: Modify flags using (:=, +=, patsubst, etc)
#
# DH_CFLAGS_GENERIC	+=
# DH_CFLAGS_DEBUG	+=
# DH_CFLAGS_RELEASE	+=
# DH_CXXFLAGS_GENERIC	+=
# DH_CXXFLAGS_DEBUG	+=
# DH_CXXFLAGS_RELEASE	+=
# DH_LDFLAGS_SHAREDLIB	+=
# DH_LDFLAGS_EXECUTABLE	+=
# DH_ARFLAGS_STATICLIB	+=

DH_LIBCURL_PREFERENCE = rootfs-linked
DH_LIBOPENSSL_PREFERENCE = rootfs-linked
DH_LIBFREETYPE_LIBFONTCONFIG_PREFERENCE = stagecraft-built

# DH_DISABLE_JIT	:= yes

###############################################################################
# STEP 3 - OPTIONAL: Modify/add modules that should be built using (:=, +=, patsubst, etc)
#
# DH_KERNEL_MODULES	+=
# DH_CORE_MODULES	+=
# DH_EDK_MODULES	+=
# DH_DDK_MODULES	+=
# DH_OSPK_MODULES	+=
# DH_STAGECRAFT_MODULES	+=
# DH_TEST_MODULES	+=
# DH_BUILD_TOOL_MODULES	+=

# for advance testing of GLES features:
#DH_DDK_MODULES	+= IGraphicsDriverGLES2

#DH_AVE_WEBKIT_MODULES += webkitapp-jspsdk

# add libffmpeg if the tarball is present
ifeq (yes, $(DH_LIBFFMPEG_PRESENT))
DH_LIBRARY_MODULES += libffmpeg
IStreamPlayer: libffmpeg
endif


$(warning "dep-all" $(dep-all))
include $(DH_PLATFORM_MAKEFILE_DIR)/apps.mk

###############################################################################
#  LOG
###############################################################################
#  26-Aug-08	dwoodward	created
#  09-Sep-08	dsletten	removed IMemGraphicsDriver
#  12-Mar-09	padolph		added curl and openssl build prefs (commented out)
#  24-Mar-09	dwoodward	conditionally add libffmpeg
#  22-Sep-09	pramod		added support for building FreeType/FontConfig
#  01-Dec-09	dsletten	libffmpeg added to DH_LIBRARY_MODULES, not to DDK
#				moved freetype/fontconfig activation to master makefile
#  27-Jul-10	dwoodward	added DH_DISABLE_JIT variable, commented out by default

